# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pr: none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5b28cb38-b92e-4af2-b272-a376a56a03d5'
  azureResourceManagerServiceConnection: '7e171f75-ea23-42dc-b642-becd86ebc3c8'
  imageRepository: 'spring'
  containerRegistry: 'jld98.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/spring/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Extract last tag from ACR
    displayName: Extract last tag from ACR
    pool:
      name: 'on-prem pool'
    steps:

    - task: AzureCLI@2
      displayName: Calculate next image version
      inputs:
        azureSubscription: $(azureResourceManagerServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          tags=$(az acr repository show-tags \
            --name jld98 \
            --repository spring \
            --output tsv)

          latest=$(printf '%s\n' "$tags" | \
            awk '/^[0-9]+$/ { if ($1 > max) max=$1 } END { print max }')

          if [ -z "$latest" ]; then
            next=1
          else
            next=$((latest + 1))
          fi

          echo "Última versión: $latest"
          echo "Nueva versión: $next"

          echo "##vso[task.setvariable variable=tag]$next"
  
  
  - job: Build and push an image to container registry
    displayName: Build and push an image to container registry
    pool:
      name: 'on-prem pool'
    steps:

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)


  - job: Build and push an image to container registry
    displayName: Build and push an image to container registry
    pool:
      name: 'on-prem pool'
    steps:

    - task: Bash@3
      displayName: Remove local application image
      inputs:
        targetType: inline
        script: |
          docker rmi jld98.azurecr.io/spring:$(tag)