# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5b28cb38-b92e-4af2-b272-a376a56a03d5'
  imageRepository: 'spring'
  containerRegistry: 'jld98.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/spring/Dockerfile'
  tag: '$(Build.BuildId)'
  poolName: 'on-prem pool'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: dockerImageBuild
  displayName: Build and push new Docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(poolName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
